# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flikas-ss

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_54030022169340f49bb1dabb970b1a4e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4ac9ccf5fe914970b0e48c09af8a3156 }}

    - run: |
        docker build . -t index.docker.io/${{ secrets.AzureAppService_ContainerUsername_54030022169340f49bb1dabb970b1a4e }}/shadowsocks-webapp:latest
        docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_54030022169340f49bb1dabb970b1a4e }}/shadowsocks-webapp:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flikas-ss'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8d4b6b2570bc47a5b00a5702dec6c4aa }}
        images: '${{ secrets.AzureAppService_ContainerUsername_54030022169340f49bb1dabb970b1a4e }}/shadowsocks-webapp:latest'
